# Site settings
name: Albin Shiby
title: Albin Shiby | Personal Page
description: FOSS Supporter, Cyber Enthusiast and Linux Nerd With A Different Vision.
url: https://bylonlog.github.io/
baseurl: ''
email: hi.bylonlog@skiff.com
cover: https://bylonlog.github.io/img/og.png
logo: https://bylonlog.github.io/img/emojis/technologist.png
resume: https://bylonlog.github.io/resume.pdf
social:
  - title: email
    url: mailto:brittany.chiang@gmail.com
  - title: twitter
    url: https://twitter.com/bylonlog
  - title: instagram
    url: https://instagram.com/bylonlog
  - title: github
    url: https://github.com/bylonlog

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
